from agents.base import BaseAgent
import config

QA_SYSTEM_PROMPT = """You are a meticulous Quality Assurance (QA) engineer and senior code reviewer.
Your job is to review work products (either implementation plans or code changes) to ensure they are high-quality, correct, safe, and address all requirements.

You must output your decision in a strict format so the orchestrator can parse it:

DECISION: APPROVED
(Use this if everything is perfect and meets the goals)

OR

DECISION: REJECTED
FEEDBACK:
- [List specific issues, bugs, or missing requirements]
- [Explain what needs to be fixed]
"""

class QAAgent(BaseAgent):
    def __init__(self, model_name: str = None):
        super().__init__(role="QA", model_name=model_name or config.QA_MODEL)

    def review_plan(self, user_request: str, proposed_plan: str, codebase_context: str) -> str:
        """
        Reviews an implementation plan proposed by the Planner.
        """
        prompt = f"""### Task Context:
User Request: {user_request}

### Existing Codebase:
{codebase_context}

### Proposed Implementation Plan:
{proposed_plan}

Please review the plan carefully. Verify:
1. Does it cover all requirements of the user request?
2. Are the proposed file paths and structure correct?
3. Does it address edge cases, safety, and testing?

Output DECISION: APPROVED or DECISION: REJECTED with feedback.
"""
        return self.call_llm(
            system_prompt=QA_SYSTEM_PROMPT,
            user_prompt=prompt,
            temperature=0.1  # Low temperature for deterministic evaluation
        )

    def review_code(self, user_request: str, approved_plan: str, code_changes: str, codebase_context: str) -> str:
        """
        Reviews code changes generated by the Developer.
        """
        prompt = f"""### Task Context:
User Request: {user_request}

### Approved Implementation Plan:
{approved_plan}

### Original Codebase:
{codebase_context}

### Generated Code Changes:
{code_changes}

Please review the code changes carefully. Verify:
1. Do the changes match the approved plan?
2. Are there syntax errors, logical bugs, or incorrect imports?
3. Did the developer output full file contents inside the required <file path="..."> tags?
4. Are edge cases handled correctly?

Output DECISION: APPROVED or DECISION: REJECTED with feedback.
"""
        return self.call_llm(
            system_prompt=QA_SYSTEM_PROMPT,
            user_prompt=prompt,
            temperature=0.1
        )
