from agents.base import BaseAgent
import config

QA_SYSTEM_PROMPT = """You are a Quality Assurance (QA) engineer.
Your job is to review work products (implementation plans or code changes) to ensure they are functionally correct, compile cleanly, and address the requirements.

You must output your decision in a strict format so the orchestrator can parse it:

DECISION: APPROVED
(Use this if everything is functionally correct and meets the goals)

OR

DECISION: REJECTED
FEEDBACK:
- [List specific issues, bugs, or missing requirements]
- [Explain what needs to be fixed]

Review Guidelines:
1. Focus strictly on correctness, completeness, and execution. Check for compile errors, crashes, missing core requirements, or broken imports.
2. Do NOT reject code for subjective design nits, cosmetic preferences, formatting details, or minor gameplay adjustments.
3. Be highly flexible: if the core logic of the step is implemented correctly and is executable, you MUST APPROVE the code. Do not reject the entire output for minor deviations, minor omissions, or formatting slips. Let any minor tweaks be handled in subsequent tasks rather than trapping the loop in reject cycles.

Logical & Runtime Checklist:
Please trace the execution flow of the code and verify:
- **Game Loops**: If the code uses Tkinter `.after()` or equivalent, make sure the loop always reschedules itself under all pathways (so it doesn't freeze or die).
- **Canvas / Resource Clearing**: When drawing elements continuously or clearing screens (e.g. canvas.delete("all")), ensure all tracking IDs are reset to None so they can be redrawn.
- **Event Bindings**: Double check event binding strings (e.g. `<space>` with lowercase s for spacebar, arrow keys capitalized) to ensure they match Tkinter requirements.
- **State Initialization**: Ensure all accessed attributes are initialized in `__init__` to avoid AttributeErrors.

---

### EXAMPLE EXPECTED FORMAT:

### EXAMPLE APPROVED OUTPUT:
DECISION: APPROVED
The implementation matches the plan perfectly and handles all edge cases correctly.

### EXAMPLE REJECTED OUTPUT:
DECISION: REJECTED
FEEDBACK:
- The developer did not output the complete file inside the <file path="..."> tags.
- Missing import statement for 'sys' on line 3.
"""

class QAAgent(BaseAgent):
    def __init__(self, model_name: str = None):
        super().__init__(role="QA", model_name=model_name or config.QA_MODEL)

    def review_plan(self, user_request: str, proposed_plan: str, codebase_context: str) -> str:
        """
        Reviews an implementation plan proposed by the Planner.
        """
        prompt = f"""### Task Context:
User Request: {user_request}

### Existing Codebase:
{codebase_context}

### Proposed Implementation Plan:
{proposed_plan}

Please review the plan carefully. Verify:
1. Does it cover all requirements of the user request?
2. Are the proposed file paths and structure correct?
3. Does it address edge cases, safety, and testing?

Output DECISION: APPROVED or DECISION: REJECTED with feedback.
"""
        return self.call_llm(
            system_prompt=QA_SYSTEM_PROMPT,
            user_prompt=prompt,
            temperature=0.1  # Low temperature for deterministic evaluation
        )

    def review_code(self, user_request: str, approved_plan: str, code_changes: str, codebase_context: str) -> str:
        """
        Reviews code changes generated by the Developer.
        """
        # Truncate approved_plan if it is too long to save context
        plan_summary = approved_plan
        if len(approved_plan) > 1500:
            plan_summary = approved_plan[:1500] + "\n... (plan truncated for context) ..."

        prompt = f"""### Task Context:
User Request: {user_request}

### Approved Plan Summary:
{plan_summary}

### Generated Code Changes:
{code_changes}

Please review the code changes carefully. Verify:
1. Do the changes match the approved plan?
2. Are there syntax errors, logical bugs, or incorrect imports?
3. Did the developer output full file contents inside the required <file path="..."> tags?
4. Are edge cases handled correctly?

Output DECISION: APPROVED or DECISION: REJECTED with feedback.
"""
        return self.call_llm(
            system_prompt=QA_SYSTEM_PROMPT,
            user_prompt=prompt,
            temperature=0.1
        )
